Repository prgrms-web-devcourse/Team_17TOP_Film_FE, pull requests merged in 2021-12, with the labels that each got.

#9 [film/#8] 프로젝트에서 사용될 font 정의
  src/App.tsx
  src/assets/fonts/SpoqaHanSansNeo-Bold.woff
  src/assets/fonts/SpoqaHanSansNeo-Light.woff
  src/assets/fonts/SpoqaHanSansNeo-Medium.woff
  src/assets/fonts/SpoqaHanSansNeo-Regular.woff
  src/assets/fonts/SpoqaHanSansNeo-Thin.woff
  src/styles/font.css
  src/styles/reset.ts
  src/styles/theme/fonts.ts
  src/styles/theme/index.ts
Labels: 리뷰 요청

#5 [film/#4] color theme 정의하기
  src/styles/theme/colors.ts
  src/styles/theme/index.ts
Labels: 리뷰 요청

#7 [film/#6] 요소들 사이의 간격을 정의하기 위한 theme을 정의한다.
  src/styles/theme/gaps.ts
  src/styles/theme/index.ts
Labels: 리뷰 요청

#12 [film/#10] Text component 제작
  src/components/atoms/Text/index.tsx
  src/components/atoms/Text/style.ts
  src/components/atoms/index.ts
Labels: 리뷰 요청

#15 [film/#14]로그인 페이지 마크업
  src/App.tsx
  src/assets/LoginPage/LoginWallPaper.jpeg
  src/index.tsx
  src/pages/DemoPage/index.tsx
  src/pages/DemoPage/style.ts
  src/pages/LoginPage/index.tsx
  src/pages/LoginPage/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
Labels: 리뷰 요청

#21 [film/#20] storybook에 emotion theme, reset 스타일 추가
  .storybook/preview.js
Labels: 리뷰 요청

#18 [Film/#17]회원가입 페이지(닉네임 입력 페이지)마크업
  package.json
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
  yarn.lock
Labels: 리뷰 요청

#22 [Film/#11] 버튼 컴포넌트 구현
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.ts
  src/components/atoms/Button/types.ts
  src/components/atoms/index.ts
  src/stories/components/Button.stories.tsx
  src/styles/reset.ts
Labels: 리뷰 요청

#25 [film/#13] Upload component 작성
  src/components/atoms/Upload/index.tsx
  src/components/atoms/Upload/style.ts
  src/components/atoms/Upload/types.ts
  src/components/atoms/index.ts
Labels: 리뷰 요청

#31 [Film/#23] 메인페이지 현재 지도 띄우기, 더미데이터로 마커 표시
  package.json
  src/assets/icons/icon_marker_close.svg
  src/assets/icons/icon_marker_open.svg
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
  yarn.lock
Labels: 리뷰 요청

#29 [Film/#19]Modal Component 제작
  public/index.html
  src/components/atoms/DemoComponent/index.tsx
  src/components/atoms/DemoComponent/style.ts
  src/components/atoms/Modal/index.tsx
  src/components/atoms/Modal/style.ts
  src/components/atoms/Modal/useClickOutSide.ts
  src/components/atoms/index.ts
  src/stories/components/Modal.stories.tsx
Labels: 리뷰 요청, 사용방법 기술

#35 [Film/#26] CreatePostPage 지도 띄우기
  src/pages/CreatePostPage/Map.tsx
  src/pages/CreatePostPage/Pin.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
Labels: 리뷰 요청

#33 [Film/#30] NavigationBar(header와 footer)컴포넌트 생성
  src/components/atoms/Navigation/FooterNavigation/index.tsx
  src/components/atoms/Navigation/FooterNavigation/style.ts
  src/components/atoms/Navigation/HeaderNavigation/index.tsx
  src/components/atoms/Navigation/HeaderNavigation/style.ts
  src/components/atoms/Navigation/index.tsx
  src/components/atoms/index.ts
  src/stories/components/FooterNavigation.stories.tsx
  src/stories/components/HeaderNavigation.stories.tsx
Labels: 리뷰 요청, 사용방법 기술

#38 [Film/#32] 필름 상태, 마커 선택 여부에 따른 핀 이미지 변경
  src/assets/icons/icon_marker_close.svg
  src/assets/icons/icon_marker_close_selected.svg
  src/assets/icons/icon_marker_open.svg
  src/assets/icons/icon_marker_open_selected.svg
  src/components/organism/Pin/index.tsx
  src/components/organism/Pin/style.ts
  src/components/organism/index.ts
  src/pages/HomePage/index.tsx
Labels: 리뷰 요청

#41 [Film/#40] 이미지 컴포넌트 제작
  src/components/atoms/Image/index.tsx
  src/components/atoms/Image/style.ts
  src/components/atoms/Image/useInterSectingObserver.ts
  src/components/atoms/index.ts
  src/stories/components/Image.stories.tsx
Labels: 리뷰 요청

#43 [film/#36] CreatePostPage 필름 내용 입력 페이지 작성
  src/components/atoms/Upload/types.ts
  src/pages/CreatePostPage/FirstStep.tsx
  src/pages/CreatePostPage/Map.tsx
  src/pages/CreatePostPage/SecondStep.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/CreatePostPage/types.ts
  src/utils/constants/mapConstants.ts
Labels: 리뷰 요청

#45 [Film/#37] 아바타, 아바타 그룹 컴포넌트 생성
  src/components/atoms/Avatar/AvatarGroup.tsx
  src/components/atoms/Avatar/constants.ts
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Avatar/style.ts
  src/components/atoms/Image/index.tsx
  src/components/atoms/index.ts
Labels: 리뷰 요청, 사용방법 기술, 재리뷰 요청

#46 [Film/#39] 엿보기 기능 구현
  src/components/organism/PreviewBottomSheet/index.tsx
  src/components/organism/PreviewBottomSheet/style.ts
  src/components/organism/index.ts
  src/pages/HomePage/index.tsx
  src/routes/Router.tsx
  src/styles/reset.ts
  src/styles/theme/fonts.ts
Labels: 재리뷰 요청, 수정완료

#51 [Film/#49] 헤더 컴포넌트 제작
  src/components/atoms/Header/components/LeftSide/index.tsx
  src/components/atoms/Header/components/LeftSide/style.ts
  src/components/atoms/Header/components/RightSide/index.tsx
  src/components/atoms/Header/components/RightSide/style.ts
  src/components/atoms/Header/index.tsx
  src/components/atoms/Header/style.ts
  src/components/atoms/index.ts
Labels: 리뷰 요청

#52 [Film/#50] 배포 시, 현재 위치 받아올 수 있도록 설정
  .github/workflows/main.yml
  package.json
Labels: 리뷰 요청

#54 [film/#44] 개봉 날짜 입력 페이지 제작
  src/assets/icons/icon_calender.svg
  src/pages/CreatePostPage/components/FirstStep.tsx
  src/pages/CreatePostPage/components/Map.tsx
  src/pages/CreatePostPage/components/Pin.tsx
  src/pages/CreatePostPage/components/SecondStep.tsx
  src/pages/CreatePostPage/components/ThirdStep.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#56 [Film/#16] 회원가입 페이지 만들기
  package.json
  src/pages/LoginPage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/style.ts
  src/pages/SignUpPage/util.ts
  src/pages/index.ts
  src/routes/Router.tsx
  src/utils/apis/user.ts
  yarn.lock
Labels: 리뷰 요청

#48 [Film/#47] 포스트페이지 헤더 제작
  src/components/atoms/Header/index.tsx
  src/components/atoms/Header/style.ts
  src/components/atoms/Navigation/HeaderNavigation/style.ts
  src/components/atoms/Navigation/index.tsx
  src/pages/CreatePostPage/components/UploadHeader/index.tsx
  src/pages/CreatePostPage/components/UploadHeader/style.ts
Labels: 재리뷰 요청, 수정완료

#58 [film/#55] ConfirmModal 제작
  src/pages/CreatePostPage/components/ConfirmModal.tsx
  src/pages/CreatePostPage/components/ThirdStep.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#61 [Film/#53] Homepage에서 Map 별도 파일로 분리
  src/components/organism/Pin/index.tsx
  src/pages/HomePage/Map.tsx
  src/pages/HomePage/index.tsx
Labels: 리뷰 요청

#62 [Film/#59] CreatePost Input validation 추가
  src/pages/CreatePostPage/components/AlertModal.tsx
  src/pages/CreatePostPage/components/SecondStep.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#68 [Film/#67] 바뀐 api에 맞게 기존 api 수정
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: 리뷰 요청

#73 [film/#72] useLocalStorage hook 제작
  src/hooks/index.ts
  src/hooks/useLocalStorage/index.ts
  src/utils/getLocalStorage.ts
Labels: 리뷰 요청

#70 [Film/#64] CreatePost Page에 헤더 추가
  src/pages/CreatePostPage/components/FirstStep.tsx
  src/pages/CreatePostPage/components/SecondStep.tsx
  src/pages/CreatePostPage/components/ThirdStep.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/style.ts
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#74 [film/#24] button 컴포넌트 타입 수정
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/types.ts
Labels: 리뷰 요청

#75 [Film/#69] axios interceptor 적용 및 회원가입페이지 에러 핸들링
  src/components/atoms/Image/useInterSectingObserver.ts
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/util.ts
  src/utils/apis/config/createInstance.ts
  src/utils/apis/config/interceptor.ts
  src/utils/apis/config/type.ts
  src/utils/apis/user.ts
  src/utils/apis/user/index.ts
  src/utils/apis/user/type.ts
Labels: 리뷰 요청

#77 [Film/#34] 오늘 열 수 있는 필름 확인하기 기능 구현
  package.json
  src/components/atoms/Modal/style.ts
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
  yarn.lock
Labels: 리뷰 요청

#78 [Film/#71] CreatePost 작성중인 내용 LocalStorage에 저장
  src/pages/CreatePostPage/components/SecondStep.tsx
  src/pages/CreatePostPage/components/ThirdStep.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#79 [Film/#66] HomePage 헤더, Post 생성 버튼 추가
  src/components/organism/PreviewBottomSheet/style.ts
  src/pages/HomePage/Map.tsx
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
Labels: 리뷰 요청

#81 [Film/#76] contextApi붙이는 작업 & 회원가입 후 userContext붙이기
  src/App.tsx
  src/contexts/DemoProvider/index.tsx
  src/contexts/DemoProvider/reducer.tsx
  src/contexts/DemoProvider/types.tsx
  src/contexts/UserProvider/index.tsx
  src/contexts/UserProvider/reducer.ts
  src/contexts/UserProvider/types.ts
  src/pages/SignUpPage/index.tsx
Labels: 리뷰 요청

#89 [Film/#82] CreatePost Page에 Api를 연결
  src/pages/CreatePostPage/components/ConfirmModal.tsx
  src/pages/CreatePostPage/components/SecondStep.tsx
  src/pages/CreatePostPage/components/ThirdStep.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/types.ts
  src/utils/apis/posts/createPostApi/index.ts
  src/utils/apis/posts/createPostApi/type.ts
  src/utils/apis/posts/index.ts
Labels: 리뷰 요청

#87 [Film/#86] PrivateRoute 설정하기
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/utils/getLocalStorage.ts
Labels: 리뷰 요청

#90 [flim/#88] 이미 있는 유저라면 context에 저장 후 페이지로 리다이렉트
  src/pages/OauthPage/index.tsx
  src/utils/apis/user/type.ts
Labels: 리뷰 요청

#95 [Film/#91] 회원가입 예외처리
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/util.ts
  src/pages/SignUpPage/util/handleApi.ts
  src/pages/SignUpPage/util/util.ts
  src/utils/apis/config/interceptor.ts
Labels: 리뷰 요청

#97 [Film/#85] HomePage Map, 엿보기 api 연동
  src/components/organism/Pin/index.tsx
  src/pages/HomePage/Map.tsx
  src/pages/HomePage/index.tsx
  src/utils/apis/post/index.ts
  src/utils/apis/post/type.ts
Labels: 리뷰 요청

#99 [Film/#80] 엿보기 페이지 포스트 데이터 바인딩, 프로필 추가
  src/assets/images/img_profile.svg
  src/components/organism/PreviewBottomSheet/index.tsx
  src/components/organism/PreviewBottomSheet/style.ts
Labels: 리뷰 요청

#98 [Film/#92] CreatePost Page localStorage에서 꺼내온 파일 정보 변환 추가
  src/pages/CreatePostPage/components/FirstStep/Map.tsx
  src/pages/CreatePostPage/components/FirstStep/Pin.tsx
  src/pages/CreatePostPage/components/FirstStep/index.tsx
  src/pages/CreatePostPage/components/SecondStep/AlertModal.tsx
  src/pages/CreatePostPage/components/SecondStep/index.tsx
  src/pages/CreatePostPage/components/ThirdStep/ConfirmModal.tsx
  src/pages/CreatePostPage/components/ThirdStep/index.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/CreatePostPage/types.ts
Labels: 리뷰 요청

#103 [Film/#96] 토스트 컴포넌트 제작
  src/components/organism/DemoComponent/index.tsx
  src/components/organism/DemoComponent/style.ts
  src/components/organism/Toast/components/ToastItem/index.tsx
  src/components/organism/Toast/components/ToastItem/style.ts
  src/components/organism/Toast/components/ToastManager/index.tsx
  src/components/organism/Toast/components/ToastManager/style.ts
  src/components/organism/Toast/index.tsx
  src/components/organism/Toast/util/useTimeout.ts
  src/components/organism/Toast/util/useTimeoutFn.ts
Labels: 리뷰 요청

#109 [film/96] close 버튼추가 및 Toast의 크기가 항상 최대폭을 가지도록 수정
  src/components/organism/Toast/components/ToastItem/index.tsx
  src/components/organism/Toast/components/ToastItem/style.ts
  src/components/organism/Toast/components/ToastManager/style.ts
Labels: 핫픽스

#107 [film/#106] CreatePost Page 경고 문구 Toast 사용하도록 변경
  src/pages/CreatePostPage/components/FirstStep/index.tsx
  src/pages/CreatePostPage/index.tsx
Labels: 리뷰 요청

#114 [film/#113] CreatePost에서 사진 업로드, 삭제 후 동일한 파일 업로드시 업데이트 되지 않던 현상 제거
  src/components/atoms/Upload/index.tsx
  src/components/atoms/Upload/types.ts
  src/pages/CreatePostPage/components/SecondStep/index.tsx
Labels: 리뷰 요청

#117 [Film/#116]로그인 로직 Toast붙이기
  src/pages/LoginPage/index.tsx
  src/pages/SignUpPage/util/handleApi.ts
  src/routes/PrivateRoute.tsx
Labels: 핫픽스

#115 [Film/#100] 엿보기 포스트 삭제 기능 구현
  src/components/organism/PreviewBottomSheet/index.tsx
  src/pages/HomePage/Modal/index.tsx
  src/pages/HomePage/Modal/style.ts
  src/pages/HomePage/index.tsx
  src/utils/apis/post/index.ts
  src/utils/apis/post/type.ts
Labels: 리뷰 요청

#120 [Film/#118] 새로고침을 해도 userContext가 유지되도록 합니다.
  src/contexts/UserProvider/index.tsx
  src/contexts/UserProvider/types.ts
  src/hooks/useLocalStorage/index.ts
  src/pages/LoginPage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/util/handleApi.ts
  src/routes/NotLoginCanUseRoute.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/utils/apis/config/constants.ts
  src/utils/apis/config/interceptor.ts
  src/utils/getLocalStorage.ts
Labels: 핫픽스

#124 [film/#118] 인증이 필요한 도메인의 경우 login 페이지로 바로 리다이렉트하도록 설정
  src/contexts/UserProvider/index.tsx
  src/hooks/useLocalStorage/index.ts
  src/pages/HomePage/index.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
Labels: 핫픽스

#125 [film/#122] Image 컴포넌트 width, height string Type 추가
  src/components/atoms/Image/index.tsx
Labels: 리뷰 요청

#121 [Film/#105] PostDetailPage 마크업, 스타일링, api 연동
  src/components/organism/PreviewBottomSheet/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/PostDetailPage/index.tsx
  src/pages/PostDetailPage/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
  src/utils/apis/post/index.ts
  src/utils/apis/post/type.ts
Labels: 리뷰 요청

#138 [film/#112] SearchUser 컴포넌트 제작
  src/components/organism/SearchUser/ResultItem/index.tsx
  src/components/organism/SearchUser/ResultItem/style.ts
  src/components/organism/SearchUser/ResultList/index.tsx
  src/components/organism/SearchUser/ResultList/style.ts
  src/components/organism/SearchUser/index.tsx
  src/components/organism/SearchUser/style.ts
Labels: 리뷰 요청

#140 [film/#139] SelectedUserList Component 제작
  src/components/organism/SelectedUserList/SelectedUserCard.tsx/index.tsx
  src/components/organism/SelectedUserList/SelectedUserCard.tsx/style.ts
  src/components/organism/SelectedUserList/index.tsx
  src/components/organism/SelectedUserList/style.ts
  src/routes/Router.tsx
Labels: 리뷰 요청

#142 [Film/#141] SelectedUserListContext 제작
  src/components/organism/SearchUser/index.tsx
  src/components/organism/SelectedUserList/SelectedUserCard.tsx/index.tsx
  src/components/organism/SelectedUserList/index.tsx
  src/contexts/SelectedUserListProvider/index.tsx
  src/contexts/SelectedUserListProvider/reducer.ts
  src/contexts/SelectedUserListProvider/type.ts
Labels: 리뷰 요청

#144 [Film/#108] CreatePostPage 열람권한 설정 마크업
  src/pages/CreatePostPage/components/ThirdStep/index.tsx
  src/pages/CreatePostPage/style.ts
Labels: 리뷰 요청

#153 [Film/#152] SearchUser에 api 연동
  src/components/organism/SearchUser/ResultItem/index.tsx
  src/components/organism/SearchUser/ResultItem/style.ts
  src/components/organism/SearchUser/ResultList/index.tsx
  src/components/organism/SearchUser/index.tsx
  src/components/organism/SelectedUserList/SelectedUserCard.tsx/index.tsx
  src/components/organism/SelectedUserList/SelectedUserCard.tsx/style.ts
  src/utils/apis/searchUser/index.ts
  src/utils/apis/searchUser/type.ts
Labels: 리뷰 요청
